# Generated by Django 4.2.4 on 2023-08-19 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя персонажа', max_length=64, unique=True, verbose_name='Персонаж')),
                ('image', models.ImageField(default=None, null=True, upload_to='charactes/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Kameo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя камео', max_length=64, unique=True, verbose_name='Камео')),
                ('image', models.ImageField(default=None, null=True, upload_to='kameos/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('input', models.CharField(max_length=480)),
                ('clip', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания тодухи')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_combos', to='combos.character')),
                ('kameo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kameo_combos', to='combos.kameo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
