# Generated by Django 4.2.4 on 2023-08-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ('name',), 'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AlterModelOptions(
            name='combo',
            options={'ordering': ('character__name',), 'verbose_name': 'Комбо', 'verbose_name_plural': 'Комбы'},
        ),
        migrations.AlterModelOptions(
            name='kameo',
            options={'ordering': ('name',), 'verbose_name': 'Камео', 'verbose_name_plural': 'Камео'},
        ),
        migrations.AddField(
            model_name='combo',
            name='clip_source',
            field=models.CharField(choices=[('Y', 'youtube'), ('T', 'twitch')], default='twitch', max_length=80),
        ),
    ]
