# Generated by Django 4.2.4 on 2023-08-21 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('combos', '0002_alter_character_options_alter_combo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название тэга', max_length=64, unique=True, verbose_name='Тэг')),
                ('color', models.CharField(max_length=7, unique=True, verbose_name='Цвет тэга')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг тэга')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.RenameField(
            model_name='combo',
            old_name='user',
            new_name='author',
        ),
        migrations.CreateModel(
            name='FavoriteCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='combos.combo', verbose_name='Комбо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_combos', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Избранное комбо',
                'verbose_name_plural': 'Избранные комбы',
            },
        ),
        migrations.AddField(
            model_name='combo',
            name='tags',
            field=models.ManyToManyField(related_name='combos', to='combos.tag', verbose_name='Тэги'),
        ),
        migrations.AddConstraint(
            model_name='favoritecombo',
            constraint=models.UniqueConstraint(fields=('user', 'combo'), name='unique_favorite_user_combo'),
        ),
    ]
